### ISSUE TITLE
Specify test path

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/NPS-generation#10]
When running `pytest`, it is best to specify the path to the tests (in our case, `tests/`), so that files that happen to be of the name `test*` but are not really tests are ignored. We can do this either by being explicit in the CI, or (the preferred way), by specifying the test path in `pyproject.toml`, so that the invocation of `pytest` on the command line picks up the correct test path from `pyproject.toml`.

**Comment by anushka255** [comment]
Removed test path from dev.yml and integrated it in pyproject.toml.
