### ISSUE TITLE
Make batch_size a parameter in sample_molecules.py

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/NPS-generation#11]
To make tests work in the CI, I made the following change in `sample_molecules.py`:

Changed
```
    batch_size = 512
```
to
```
    batch_size = 32
```

The general rationale for this was to reduce the amount of "work" the model has to perform in one go (and thus reduce the computational complexity and memory requirements of the model). Not 100% scientific way of doing things, but this does demonstrate the mantra that it is okay to fix things by making tiny tweaks (and documenting them), even if we can't explain them satisfactorily, instead of getting stuck in an undesirable situation. Having the CI fail is one of those situations.

With this "fix" working, the correct way to do this of course would be to expose `batch_size` as a parameter, reset its default value to `512` (to not affect legacy behavior), and having it overridden in our test case.

**Comment by anushka255** [comment]
Made batch_size a parameter with a default value of 512.

**Comment by vineetbansal** [comment]
Thanks!
